# Generated by Django 3.1.7 on 2021-04-26 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentBreakUP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_Method', models.CharField(max_length=100)),
                ('payment', models.IntegerField()),
                ('ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.salesbooking')),
            ],
        ),
    ]
