# Generated by Django 3.1.7 on 2021-04-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_createpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpayment',
            name='Difference',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='createpayment',
            name='Total_Amount',
            field=models.IntegerField(null=True),
        ),
    ]
