# Generated by Django 3.1.7 on 2021-04-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_createpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpayment',
            name='Date',
            field=models.DateField(null=True),
        ),
    ]
