# Generated by Django 3.1.7 on 2021-04-30 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('account', '0004_auto_20210429_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createpayment',
            name='Difference',
        ),
        migrations.RemoveField(
            model_name='createpayment',
            name='Total_Amount',
        ),
        migrations.CreateModel(
            name='TotalPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Payment', models.IntegerField()),
                ('Difference', models.IntegerField()),
                ('Payment_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.salesbooking')),
            ],
        ),
    ]
