# Generated by Django 3.1.7 on 2021-04-30 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('account', '0006_auto_20210430_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Payment', models.IntegerField(null=True)),
                ('Difference', models.IntegerField(null=True)),
                ('Payment_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.salesbooking')),
            ],
        ),
    ]
