# Generated by Django 3.1.7 on 2021-04-30 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_totalpayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='totalpayment',
            old_name='Payment_ID',
            new_name='Booking_ID',
        ),
        migrations.RemoveField(
            model_name='createpayment',
            name='Difference',
        ),
        migrations.RemoveField(
            model_name='createpayment',
            name='Total_Amount',
        ),
    ]
