# Generated by Django 3.1.7 on 2021-05-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20210430_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalpayment',
            name='Payment_Status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
