# Generated by Django 3.1.7 on 2021-03-11 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel')], max_length=20)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('transmission', models.CharField(choices=[('MT', 'MT'), ('AMT', 'AMT')], max_length=20)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.brand')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.fuel')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.model')),
            ],
        ),
        migrations.AddField(
            model_name='fuel',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.model'),
        ),
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('typecode', models.CharField(choices=[('Pearl', 'Pearl'), ('Flat', 'Flat')], max_length=20)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.brand')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.fuel')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.model')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.variant')),
            ],
        ),
    ]
