# Generated by Django 3.1.7 on 2021-03-25 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('typecode', models.CharField(choices=[('Pearl', 'Pearl'), ('Flat', 'Flat')], max_length=20)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Dealership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel')], max_length=20, unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.brand')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.fuel')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.model')),
            ],
        ),
        migrations.AddField(
            model_name='fuel',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.model'),
        ),
        migrations.CreateModel(
            name='Dealbreakup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmission', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=20)),
                ('ex_Showroom_Price', models.FloatField()),
                ('ins_AMT', models.FloatField()),
                ('rto', models.FloatField()),
                ('fASTag', models.FloatField()),
                ('tcs', models.FloatField()),
                ('total', models.FloatField()),
                ('acc', models.FloatField()),
                ('extended_Warranty', models.FloatField()),
                ('amc', models.FloatField()),
                ('on_Road_Price', models.FloatField()),
                ('consume_offer', models.FloatField(default=0)),
                ('exchange_bonus', models.FloatField(default=0)),
                ('corporate_discount', models.FloatField(default=0)),
                ('remarks', models.CharField(max_length=50)),
                ('dealer_discount', models.FloatField(default=0)),
                ('total_discount', models.FloatField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.brand')),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.colour')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.fuel')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.model')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.variant')),
            ],
        ),
        migrations.AddField(
            model_name='colour',
            name='fuel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.fuel'),
        ),
        migrations.AddField(
            model_name='colour',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.model'),
        ),
        migrations.AddField(
            model_name='colour',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.variant'),
        ),
    ]
