# Generated by Django 3.1.7 on 2021-03-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='transmission',
        ),
        migrations.AddField(
            model_name='colour',
            name='transmission',
            field=models.CharField(choices=[('MT', 'MT'), ('AMT', 'AMT')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
