# Generated by Django 3.1.7 on 2021-03-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20210312_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colour',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=20),
        ),
    ]
