# Generated by Django 3.1.7 on 2021-03-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20210331_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='Name',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel')], max_length=20, unique=True),
        ),
    ]
