# Generated by Django 3.1.7 on 2021-03-15 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_auto_20210315_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealbreakup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ex_Showroom_Price', models.FloatField()),
                ('Ins_AMT', models.FloatField()),
                ('Rto', models.FloatField()),
                ('FASTag', models.FloatField()),
                ('Tcs', models.FloatField()),
                ('Total', models.FloatField()),
                ('Acc', models.FloatField()),
                ('Extended_Warranty', models.FloatField()),
                ('Amc', models.FloatField()),
                ('On_Road', models.FloatField()),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.brand')),
                ('Colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.colour')),
                ('Fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.fuel')),
                ('Model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.model')),
                ('Variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.variant')),
            ],
        ),
    ]
