# Generated by Django 3.1.7 on 2021-03-15 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_dealbreakup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealbreakup',
            old_name='On_Road',
            new_name='On_Road_Price',
        ),
    ]
