# Generated by Django 3.1.7 on 2021-03-16 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_auto_20210315_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colour',
            name='transmission',
        ),
        migrations.AddField(
            model_name='dealbreakup',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
