# Generated by Django 3.1.7 on 2021-04-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_auto_20210401_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='Name',
            new_name='Brand_Name',
        ),
        migrations.RenameField(
            model_name='colour',
            old_name='Name',
            new_name='Colour',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='Name',
            new_name='Variant',
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='Name',
        ),
        migrations.AddField(
            model_name='fuel',
            name='Fuel_Type',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
