# Generated by Django 3.1.7 on 2021-04-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_auto_20210401_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='Brand_Name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='colour',
            old_name='Colour',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='Model',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='Variant',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='Fuel_Type',
        ),
        migrations.AddField(
            model_name='fuel',
            name='Name',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
