# Generated by Django 3.1.7 on 2021-03-16 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_auto_20210316_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealbreakup',
            old_name='Acc',
            new_name='acc',
        ),
        migrations.RenameField(
            model_name='dealbreakup',
            old_name='Amc',
            new_name='amc',
        ),
        migrations.RenameField(
            model_name='dealbreakup',
            old_name='Brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='dealbreakup',
            old_name='Colour',
            new_name='colour',
        ),
        migrations.RenameField(
            model_name='dealbreakup',
            old_name='Ex_Showroom_Price',
            new_name='ex_Showroom_Price',
        ),
        migrations.RenameField(
            model_name='dealbreakup',
            old_name='Extended_Warranty',
            new_name='extended_Warranty',
        ),
        migrations.RenameField(
            model_name='dealbreakup',
            old_name='FASTag',
            new_name='fASTag',
        ),
        migrations.RenameField(
            model_name='dealbreakup',
            old_name='Fuel',
            new_name='fuel',
        ),
        migrations.RenameField(
            model_name='dealbreakup',
            old_name='Ins_AMT',
            new_name='ins_AMT',
        ),
        migrations.RenameField(
            model_name='dealbreakup',
            old_name='Model',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='dealbreakup',
            old_name='On_Road_Price',
            new_name='on_Road_Price',
        ),
        migrations.RenameField(
            model_name='dealbreakup',
            old_name='Rto',
            new_name='rto',
        ),
        migrations.RenameField(
            model_name='dealbreakup',
            old_name='Tcs',
            new_name='tcs',
        ),
        migrations.RenameField(
            model_name='dealbreakup',
            old_name='Total',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='dealbreakup',
            old_name='Variant',
            new_name='variant',
        ),
    ]
