# Generated by Django 3.1.7 on 2021-04-08 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_auto_20210402_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuel',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='model',
        ),
    ]
