# Generated by Django 3.1.7 on 2021-04-08 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0011_auto_20210408_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealbreakup',
            old_name='Annual_Maintance_Cost',
            new_name='Annual_Maintanence_Cost',
        ),
    ]
