# Generated by Django 3.1.7 on 2021-03-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0012_auto_20210320_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='Name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='colour',
            name='Name',
            field=models.CharField(max_length=20),
        ),
    ]
