# Generated by Django 3.1.7 on 2021-04-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0013_auto_20210414_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='Name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='colour',
            name='Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='model',
            name='Name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
