# Generated by Django 3.1.7 on 2021-03-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0015_auto_20210320_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='Name',
            field=models.CharField(max_length=20),
        ),
    ]
