# Generated by Django 3.1.7 on 2021-04-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0015_auto_20210421_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealbreakup',
            name='Minimum_Margin',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dealbreakup',
            name='Purchase_Price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
