# Generated by Django 3.1.7 on 2021-03-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0020_dealership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealership',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
