# Generated by Django 3.1.7 on 2021-04-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadRTO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RTO', models.FileField(upload_to='')),
                ('Insurance', models.FileField(upload_to='')),
            ],
        ),
    ]
