# Generated by Django 3.1.7 on 2021-04-21 07:16

from django.db import migrations, models
import django.db.models.deletion
import sales.models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_salesbooking_cash_rtgs_neft'),
        ('edp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='ID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sales.salesbooking'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='Tally',
            field=models.FileField(blank=True, null=True, upload_to=sales.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='DMS',
            field=models.FileField(blank=True, null=True, upload_to=sales.models.user_directory_path),
        ),
    ]
