# Generated by Django 3.1.7 on 2021-04-21 09:18

from django.db import migrations, models
import edp.models


class Migration(migrations.Migration):

    dependencies = [
        ('edp', '0002_auto_20210421_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='DMS',
            field=models.FileField(default=0, upload_to=edp.models.user_directory_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='Tally',
            field=models.FileField(default=0, upload_to=edp.models.user_directory_path),
            preserve_default=False,
        ),
    ]
