# Generated by Django 3.1.7 on 2021-05-01 03:38

from django.db import migrations, models
import edp.models


class Migration(migrations.Migration):

    dependencies = [
        ('edp', '0002_uploadrto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadRTO',
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='Insurance',
            field=models.FileField(blank=True, null=True, upload_to=edp.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='RTO',
            field=models.FileField(blank=True, null=True, upload_to=edp.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='DMS',
            field=models.FileField(blank=True, null=True, upload_to=edp.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='Tally',
            field=models.FileField(blank=True, null=True, upload_to=edp.models.user_directory_path),
        ),
    ]
