# Generated by Django 3.1.7 on 2021-04-21 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edp', '0003_auto_20210421_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='ID',
        ),
    ]
