# Generated by Django 3.1.7 on 2021-05-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edp', '0003_auto_20210501_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='DMS_Tally_Status',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
