# Generated by Django 3.1.7 on 2021-04-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edp', '0004_remove_uploadfile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='DMS',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='Tally',
            field=models.FileField(upload_to=''),
        ),
    ]
