# Generated by Django 3.1.7 on 2021-04-21 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_salesbooking_cash_rtgs_neft'),
        ('edp', '0005_auto_20210421_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='ID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sales.salesbooking'),
            preserve_default=False,
        ),
    ]
