# Generated by Django 3.1.7 on 2021-04-21 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_salesbooking_cash_rtgs_neft'),
        ('edp', '0006_uploadfile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='ID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.salesbooking'),
        ),
    ]
