# Generated by Django 3.1.7 on 2021-04-21 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_salesbooking_cash_rtgs_neft'),
        ('edp', '0008_auto_20210421_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.salesbooking'),
        ),
    ]
