# Generated by Django 3.1.7 on 2021-04-07 09:46

from django.db import migrations, models
import django.db.models.deletion
import sales.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0009_auto_20210402_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salesbooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_ID', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Ex_Showroom_Price', models.FloatField()),
                ('Ins_AMT', models.FloatField()),
                ('Rto', models.FloatField()),
                ('FASTag', models.FloatField()),
                ('Tcs', models.FloatField()),
                ('Total', models.FloatField()),
                ('Acc', models.FloatField()),
                ('Extended_Warranty', models.FloatField()),
                ('Amc', models.FloatField()),
                ('On_Road_Price', models.FloatField()),
                ('booking_receipt', models.FileField(blank=True, null=True, upload_to=sales.models.user_directory_path)),
                ('quotation', models.FileField(blank=True, null=True, upload_to=sales.models.user_directory_path)),
                ('order_form', models.FileField(blank=True, null=True, upload_to=sales.models.user_directory_path)),
                ('Delivery_Order', models.FileField(blank=True, null=True, upload_to=sales.models.user_directory_path)),
                ('Consumer_offer', models.FloatField(default=0)),
                ('Exchange_bonus', models.FloatField(default=0)),
                ('Corporate_discount', models.FloatField(default=0)),
                ('Remarks', models.CharField(max_length=50)),
                ('Dealer_discount', models.FloatField(default=0)),
                ('Total_discount', models.FloatField(default=0)),
                ('Down_Payment', models.FloatField()),
                ('Finance', models.FloatField()),
                ('Used_car', models.FloatField()),
                ('Total_Payment', models.FloatField()),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('Modification', models.TextField(blank=True, max_length=100, null=True)),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.brand')),
                ('Colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.colour')),
                ('Model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.model')),
                ('Variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.variant')),
            ],
        ),
    ]
