# Generated by Django 3.1.7 on 2021-03-18 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_auto_20210318_1450'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesbooking',
            name='Acc',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salesbooking',
            name='Amc',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salesbooking',
            name='Colour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.colour'),
        ),
        migrations.AlterField(
            model_name='salesbooking',
            name='Ex_Showroom_Price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salesbooking',
            name='Extended_Warranty',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salesbooking',
            name='FASTag',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salesbooking',
            name='Ins_AMT',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salesbooking',
            name='Model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.model'),
        ),
        migrations.AlterField(
            model_name='salesbooking',
            name='On_Road_Price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salesbooking',
            name='Rto',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salesbooking',
            name='Tcs',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salesbooking',
            name='Total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salesbooking',
            name='Variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.variant'),
        ),
    ]
