# Generated by Django 3.1.7 on 2021-04-08 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20210408_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesbooking',
            old_name='Annual_Maintance_Cost',
            new_name='Annual_Maintanence_Cost',
        ),
    ]
