# Generated by Django 3.1.7 on 2021-03-18 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_auto_20210318_1450'),
        ('sales', '0002_auto_20210318_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesbooking',
            name='Brand',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='master.brand'),
            preserve_default=False,
        ),
    ]
