# Generated by Django 3.1.7 on 2021-04-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20210408_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesbooking',
            name='Down_Payment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesbooking',
            name='Finance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesbooking',
            name='Total_Payment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesbooking',
            name='Used_car',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
