# Generated by Django 3.1.7 on 2021-03-31 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salesbooking_dealership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesbooking',
            name='Dealership',
        ),
    ]
