# Generated by Django 3.1.7 on 2021-03-31 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('sales', '0004_remove_salesbooking_dealership'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesbooking',
            name='Dealership',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='master.dealership'),
            preserve_default=False,
        ),
    ]
