# Generated by Django 3.1.7 on 2021-04-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20210412_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModificationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Modification', models.TextField(max_length=200)),
            ],
        ),
    ]
