# Generated by Django 3.1.7 on 2021-03-31 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('sales', '0005_salesbooking_dealership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesbooking',
            name='Dealership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.dealership'),
        ),
    ]
