# Generated by Django 3.1.7 on 2021-04-12 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_modificationdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesbooking',
            name='Modification',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.modificationdetails'),
        ),
    ]
