# Generated by Django 3.1.7 on 2021-03-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20210323_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesbooking',
            name='booking_ID',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
