# Generated by Django 3.1.7 on 2021-04-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_auto_20210412_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesbooking',
            name='Modification',
            field=models.TextField(default=0, help_text='Write Something', max_length=500),
            preserve_default=False,
        ),
    ]
