# Generated by Django 3.1.7 on 2021-03-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_auto_20210323_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesbooking',
            name='booking_receipt',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='salesbooking',
            name='order_form',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='salesbooking',
            name='quotation',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
