# Generated by Django 3.1.7 on 2021-04-12 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_auto_20210412_1642'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModificationDetails',
        ),
    ]
