# Generated by Django 3.1.7 on 2021-04-03 11:26

from django.db import migrations, models
import sales.models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_remove_salesbooking_dealer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesbooking',
            name='Delivery_Order',
            field=models.FileField(blank=True, default='Missing', null=True, upload_to=sales.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='salesbooking',
            name='booking_receipt',
            field=models.FileField(blank=True, default='Missing', null=True, upload_to=sales.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='salesbooking',
            name='order_form',
            field=models.FileField(blank=True, default='Missing', null=True, upload_to=sales.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='salesbooking',
            name='quotation',
            field=models.FileField(blank=True, default='Missing', null=True, upload_to=sales.models.user_directory_path),
        ),
    ]
