# Generated by Django 3.1.7 on 2021-04-03 11:31

from django.db import migrations, models
import sales.models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_auto_20210403_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesbooking',
            old_name='Consume_offer',
            new_name='Consumer_offer',
        ),
        migrations.AlterField(
            model_name='salesbooking',
            name='Delivery_Order',
            field=models.FileField(blank=True, null=True, upload_to=sales.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='salesbooking',
            name='booking_receipt',
            field=models.FileField(blank=True, null=True, upload_to=sales.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='salesbooking',
            name='order_form',
            field=models.FileField(blank=True, null=True, upload_to=sales.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='salesbooking',
            name='quotation',
            field=models.FileField(blank=True, null=True, upload_to=sales.models.user_directory_path),
        ),
    ]
