# Generated by Django 3.1.7 on 2021-04-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_delete_modificationdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesbooking',
            name='Down_Payment',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesbooking',
            name='Finance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesbooking',
            name='Total_Payment',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesbooking',
            name='Used_car',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
