# Generated by Django 3.1.7 on 2021-04-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_auto_20210403_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesbooking',
            name='Down_Payment',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesbooking',
            name='Finance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesbooking',
            name='Used_car',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
