# Generated by Django 3.1.7 on 2021-04-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_auto_20210414_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesbooking',
            name='Consumer_offer',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salesbooking',
            name='Corporate_discount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salesbooking',
            name='Dealer_discount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salesbooking',
            name='Exchange_bonus',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salesbooking',
            name='Remarks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salesbooking',
            name='Total_discount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
