# Generated by Django 3.1.7 on 2021-04-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_auto_20210405_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesbooking',
            name='Total_Payment',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
