# Generated by Django 3.1.7 on 2021-04-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_auto_20210414_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesbooking',
            name='Consumer_offer',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salesbooking',
            name='Corporate_discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salesbooking',
            name='Dealer_discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salesbooking',
            name='Exchange_bonus',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salesbooking',
            name='Remarks',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesbooking',
            name='Total_discount',
            field=models.FloatField(default=0),
        ),
    ]
