# Generated by Django 3.1.7 on 2021-04-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_salesbooking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesbooking',
            name='Status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=50, null=True),
        ),
    ]
