# Generated by Django 3.1.7 on 2021-04-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_auto_20210414_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesbooking',
            name='Modification',
            field=models.TextField(blank=True, default=0, help_text='Write Something', max_length=500),
            preserve_default=False,
        ),
    ]
