# Generated by Django 3.1.7 on 2021-04-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_auto_20210415_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesbooking',
            old_name='ACC',
            new_name='ACCESSORIES',
        ),
        migrations.RemoveField(
            model_name='salesbooking',
            name='TOTAL',
        ),
        migrations.AddField(
            model_name='salesbooking',
            name='Other',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salesbooking',
            name='Modification',
            field=models.TextField(blank=True, help_text='Write if you want to modify something!', max_length=500),
        ),
    ]
