# Generated by Django 3.1.7 on 2021-04-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_auto_20210421_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesbooking',
            name='Cash_RTGS_NEFT',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
